version: '3.1'

services:

  redmine:
    build:
      context: .
    image: redmine-custom
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: essess
      REDMINE_SECRET_KEY_BASE: essess
    depends_on:
      - db
    volumes:
      - redmine_data:/usr/src/redmine/files

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: essess
      MYSQL_DATABASE: redmine
    volumes:
      - db_data:/var/lib/mysql

volumes:
  redmine_data:
  db_data:
